[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
economy = "G1mxe2u3yQEAM1fzqE6F3WL44QbMSnomfLqRyKpHo6Xs"
movement = "H4z5teSN2Lc4hNyFcTdmWb8EBxyRXUqtBRNV2jdqxFUo"
lottery_prize = "Fb1XCkDHRcTedV7UEU4yjMbytqC3HJzqxRwobnLAsipE"
ownership = "5tnVfBszH3gaVqXgWJ3cNDenZwU1ThwfBHL323SihDaa"
position = "BL5C5RUqP8zE8EY9G1268Z5zvuj6SHRcKcDf7i4Pfv9j"
price = "4kqUinqtCWkiqpxpdC8FjBmwEFSdckpyMStRPwqEQ1U3"
price-action = "4qjf6jiDRxFwTkKKy6hPS5NP5rKK9KEFCEGQAGFfLgs8"
production = "ET9h3CitgureNw7GRGTCG4hDKGTxtE1kYmPwDB6Xb1ar"
resource-production = "3Erv5Y7amyL9MNGy83HAVaQaAohQZF9qC6faHrcE58Ez"
stakeable = "7kx8P61SHK4uAzxCQuHw25WC9vnKYbWsepSMnES5muT9"
upgrade = "EtvUjVbFTusfQCsz7kReDepfERFuCnPYBHJRZNWjA6q9"
upgradeable = "EtUh4iAFPwhUSFPGCjmNdx9M36AiqUHB7QcLNmuyWVox"
wallet = "8nrcTHv976M5VozmZQ86akuyo4MZPjdwctuDjE8wqLXm"
yield_wars_program = "3gnT2CxCTT6QBZHyqtETVnhxfHBK3wccAYqfxq4Xn8PT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*", "programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[[test.genesis]]
address = "Vrf1RNUjXmQGjmQrQLvJHs9SNkvDJEsRVFPkfSQUwGz"
program = "tests/fixtures/ephemeral_vrf_program.so"
upgradeable = false

[[test.genesis]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
program = "tests/fixtures/dlp.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"

[[test.validator.account]]
address = "GKE6d7iv8kCBrsxr78W3xVdjGLLLJnxsGiuzrsZCGEvb"
filename = "tests/fixtures/oracles.json"

[[test.validator.account]]
address = "CXMc1eCiEp9YXjanBNB6HUvbWCmxeVmhcR3bPXw8exJA"
filename = "tests/fixtures/oracle_data.json"

[[test.validator.account]]
address = "GKE6d7iv8kCBrsxr78W3xVdjGLLLJnxsGiuzrsZCGEvb"
filename = "tests/fixtures/oracle_queue.json"